[window]
dimensions = { columns = 100, lines = 25 }
padding = { x = 12, y = 12 }
decorations_theme_variant = "Dark"

[font]
normal = { family = "Iosevka", style = "Regular"}
size = 12

[colors]
cursor = { text = "#fcbb6a", cursor = "#f9ae58" }
selection = { text = "#d8dee9", background = "#4e5a65" }

[colors.primary]
foreground = "#d8dee9"
background = "#343d46"

[colors.normal]
black = "#000000"
red = "#ec5f66"
green = "#99c794"
yellow = "#f9ae58"
blue = "#6699cc"
magenta = "#c695c6"
cyan = "#5fb4b4"
white = "#f7f7f7"

[colors.bright]
black = "#808080"
red = "#f97b58"
green = "#acd1a8"
yellow = "#fac761"
blue = "#85add6"
magenta = "#d8b6d8"
cyan = "#82c4c4"
white = "#ffffff"

[terminal.shell]
program = "C:\\Windows\\System32\\wsl.exe"
args = ["~", "-d Arch"]
